global:
  pattern: ramendr-starter-kit
  vpNewFolderDir: true
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  hub:
    provider: aws
main:
  variant: drpartner-s4
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
